### ISSUE TITLE
[bug]: Cannot install package

### ISSUE THREAD

**Issue by StructuralRealist** [strapi/blocks-react-renderer#34] opened 2024-04-16 09:01 UTC
### What version of `@strapi/blocks-react-renderer` are you using?

- npm v10.5.0
- node v20.12.1

### What's Wrong?

npm i @strapi/blocks-react-renderer
npm ERR! code 127
npm ERR! path ###/node_modules/@strapi/blocks-react-renderer
npm ERR! command failed
npm ERR! command sh -c husky install
npm ERR! sh: husky: command not found

### To Reproduce

- npm init -y
- npm i @strapi/blocks-react-renderer

### Expected Behaviour

I expect to be able to install the package without installing husky.

**Comment by joshuaellis** [comment] 2024-04-16 10:19
duplicate of #30

**Closed by joshuaellis** 2024-04-16 10:19 UTC
Labels: issue: bug, status: duplicate
