### ISSUE TITLE
Error installing @strapi/blocks-react-renderer package

### ISSUE THREAD

**Issue by navid-shakibayi** [strapi/blocks-react-renderer#35] opened 2024-04-30 11:26 UTC
I encountered an error code 127 while installing the @strapi/blocks-react-renderer package using the command:
`npm install @strapi/blocks-react-renderer react react-dom`
After researching online, I discovered that I needed to install the husky package. I ran the following command:
`sudo npm install -g husky`
The command completed successfully with the message:

> changed 1 package in 2s

1 package is looking for funding
 run `npm fund` for details

However, when I tried to install the @strapi/blocks-react-renderer package again, I received the following error:

> npm ERR! code 1
npm ERR! path /home/navid/navid/web-development/my-portfolio/node_modules/@strapi/blocks-react-renderer
npm ERR! command failed
npm ERR! command sh -c husky install
npm ERR! A complete log of this run can be found in: /home/navid/.npm/_logs/2024-04-30T11_16_55_075Z-debug-0.log

**Comment by joshuaellis** [comment] 2024-04-30 11:37
duplicate of #30

**Closed by joshuaellis** 2024-04-30 11:37 UTC
Labels: flag: invalid template, status: duplicate
